name: Detekt

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Detekt Verification
        run: ./gradlew detekt
